# Generated by Django 5.2.8 on 2025-11-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALAXIA', 'Galáxia'), ('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela'), ('COMETA', 'Cometa'), ('ASTEROIDE', 'Asteroide')], default='', max_length=100),
        ),
    ]
